version: '3.3'

services:

  jnetwork:
    container_name: jnetwork
    build:
      context: .
    networks:
      vpnet:
        ipv4_address: 11.12.0.3

networks:
  vpnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.12.0.0/24
          gateway: 11.12.0.1